### ISSUE TITLE
Generic SVD interface forces Σ to be a Matrix

### ISSUE THREAD

**Issue by slmcbane** [LLNL/libROM#11]
Title. Is there a good reason that we should force the SVD algorithm to return singular values in a dense matrix instead of as a vector?

**Comment by chldkdtn** [comment]
I do not see a good reason. @goxberry and @rw-anderson What do you think?

**Comment by goxberry** [comment]
One of the steps of the incremental SVD algorithm requires an SVD of a block matrix, and one of those blocks is the diagonal matrix of singular values, so the existing code was probably written in order to make forming that block matrix easier. This usage sort of offsets the argument that returning the singular values in a vector uses less memory, because we'll be coercing that data into a dense matrix anyway in the main use case of the "static" SVD.

I'm not terribly concerned about performance beyond decisions that have obvious impacts. My main concern with such a change would be how it affects existing code and future code maintenance. If the changes required to return singular values in a vector can be made without introducing errors into the code and the interfaces across the various SVDs are consistent, then I'm happy to approve those changes.

**Comment by slmcbane** [comment]
I see, that use case makes sense. If there's not too much concern with performance I won't suggest implementing a subtype `Diagonal` of `Matrix` that optimizes operations. It would be a fairly large change to introduce, with a fairly broad interface to write tests for.
